# Generated by Django 3.1.1 on 2020-09-10 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectInfoModel',
            new_name='ProjectInfo',
        ),
    ]
